// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAibYJ3lrWeQRGLM8m00MCajBQ1T-k5vwQ',
    appId: '1:79642509790:web:a933c9ebd7b9c3501a1d4f',
    messagingSenderId: '79642509790',
    projectId: 'mvvmriverpod',
    authDomain: 'mvvmriverpod.firebaseapp.com',
    storageBucket: 'mvvmriverpod.firebasestorage.app',
    measurementId: 'G-YX8FYKL86C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU_w9USn6jXQOHMZK3yv6hDK2O-xgT_TI',
    appId: '1:79642509790:android:6d8503de16a301db1a1d4f',
    messagingSenderId: '79642509790',
    projectId: 'mvvmriverpod',
    storageBucket: 'mvvmriverpod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAafhnjFLF0fLCd-f7UaErQrnB7D7oEI5o',
    appId: '1:79642509790:ios:00f1d5eef32461c01a1d4f',
    messagingSenderId: '79642509790',
    projectId: 'mvvmriverpod',
    storageBucket: 'mvvmriverpod.firebasestorage.app',
    iosBundleId: 'com.example.statemanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAafhnjFLF0fLCd-f7UaErQrnB7D7oEI5o',
    appId: '1:79642509790:ios:00f1d5eef32461c01a1d4f',
    messagingSenderId: '79642509790',
    projectId: 'mvvmriverpod',
    storageBucket: 'mvvmriverpod.firebasestorage.app',
    iosBundleId: 'com.example.statemanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAibYJ3lrWeQRGLM8m00MCajBQ1T-k5vwQ',
    appId: '1:79642509790:web:e0982912f4e79dfc1a1d4f',
    messagingSenderId: '79642509790',
    projectId: 'mvvmriverpod',
    authDomain: 'mvvmriverpod.firebaseapp.com',
    storageBucket: 'mvvmriverpod.firebasestorage.app',
    measurementId: 'G-NVRHGY173E',
  );
}
